[package]
name = "remux"
version = "0.0.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = { version = "0.5.0", features = [ "combined-flags", "eq-separator" ] }
ratatui = { version = "0.20.1", features = [ "termion" ] }
termion = "2.0.1"
tmux_interface = "0.2.1"

